<?php
/**
 * @file Main module file
 */

/**
 * Implementation of hook_menu().
 */
function cfdr_menu() {
  $menu = array();
  $menu['cfdr'] = array(
    'title' => 'View CFDs',
    'description' => 'View all CFDs',
    'access callback' => 'user_access',
    'access arguments' => array('view any FEs'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cfdr_view_cfds'),
  );
  $menu['cfdr/%/pdf'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Download',
    'access callback' => 'user_access',
    'access arguments' => array('view any FEs'),
    'page callback' => 'cfdr_download_pdf',
    'page arguments' => array(1),
  );
  $menu['cfdr/%/xml'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Download',
    'access callback' => 'user_access',
    'access arguments' => array('view any FEs'),
    'page callback' => 'cfdr_download_xml',
    'page arguments' => array(1),
  );
  $menu['cfdr/%cfdr'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'View CFD',
    'access callback' => 'user_access',
    'access arguments' => array('view any FEs'),
    'page callback' => 'cfdr_view_html',
    'page arguments' => array(1),
  );
  //Admin menu
  $menu['admin/settings/cfdr'] = array(
    'title' => 'CFD - Received Settings',
    'description' => 'Configure CFD - Received options',
    'access callback' => 'user_access',
    'access arguments' => array('administer cfdr'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cfdr_admin_form'),
    'file' => './cfdr.admin.inc',
  );
  return $menu;
}

/**
 * Implementation of hook_theme()
 **/
function cfdr_theme() {
  return array(
    'cfdr_view_cfds' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function cfdr_perm() {
  return array('administer cfdr', 'view any CFD');
}

/**
 * Saves a fully loaded cfdr object to {cfdr}
 **/
function cfdr_save(&$cfdr) {
  drupal_write_record('cfdr', $cfdr);
}

/**
 * Loads then inserts a CFD into de database.
 * @param string $cfdr_filename the full path and name of the CFD's .xml file
 **/
function cfdr_insert($filename) {
  //parse XML file read (with xml DOM(simpleXML sucks at namespaces))
  $doc = new DOMDocument();
  @$doc->load($filename, LIBXML_NOWARNING);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/2');
  $serie = $xpath->query('/cfd:Comprobante/@serie');
  $folio = $xpath->query('/cfd:Comprobante/@folio');
  $receptor_rfc = $xpath->query('/cfd:Comprobante/cfd:Receptor/@rfc');
  $emisor_rfc = $xpath->query('/cfd:Comprobante/cfd:Emisor/@rfc');
  $fecha_cfd = $xpath->query('/cfd:Comprobante/@fecha');

  $cfdr = new stdClass();
  $cfdr->serie = $serie->item(0)->value;
  $cfdr->folio = $folio->item(0)->value;
  $cfdr->receptor_rfc = $receptor_rfc->item(0)->value;
  $cfdr->emisor_rfc = $emisor_rfc->item(0)->value;
  $cfdr->fecha_cfd = $fecha_cfd->item(0)->value;
  $cfdr->xml_filename = $filename;

  cfdr_save($cfdr);
}

/**
 * Loads a cfdr object and returns it
 * @param int $cfdr_id Id of the CFD to retreive
 * @return stdObject a loaded node-like object.
 */
function cfdr_load($cfdr_id) {
  return db_fetch_object(db_query('SELECT * FROM {cfdr} WHERE cfdr_id = %d', $cfdr_id));
}

/**
 * Returns the filename of a CFD
 * @param int $cfdr_id Id of the CFD to retreive
 */
function cfdr_load_filename($cfdr_id) {
  return db_result(db_query('SELECT xml_filename FROM {cfdr} WHERE cfdr_id = %d', $cfdr_id));
}

function theme_cfdr_view_cfds($form) {
  //based on theme_node_admin_nodes() in core - node.admin.inc
  // If there are rows in this form, then $form['title'] contains a list of
  // the title form elements.
  $has_posts = isset($form['list']['serie']) && is_array($form['list']['serie']);
  $header = array('Serie', 'Folio', t('Emisor'), t('Date'), t('Receptor'), t('Download'));

  $output = '';

  $output .= drupal_render($form['date_filter']);
  if ($has_posts) {
    foreach (element_children($form['list']['serie']) as $key) {
      $row = array();
      $row[] = drupal_render($form['list']['serie'][$key]);
      $row[] = drupal_render($form['list']['folio'][$key]);
      $row[] = drupal_render($form['list']['emisor_rfc'][$key]);
      $row[] = drupal_render($form['list']['date'][$key]);
      $row[] = drupal_render($form['list']['receptor_rfc'][$key]);
      $row[] = drupal_render($form['list']['links'][$key]);
      $rows[] = $row;
    }
  }
  else {
    $rows[] = array(array('data' => t('No CFDs available.'), 'colspan' => '6'));
  }

  $output .= theme('table', $header, $rows);
  if ($form['pager']['#value']) {
    $output .= drupal_render($form['pager']);
  }

  $output .= drupal_render($form);

  return $output;
}

/**
 * 'cfdr' menu entry callback
 **/
function cfdr_view_cfds() {
  $results = pager_query('SELECT * FROM {cfdr}', 30);
  // construct the list
  $list = array();
  while ($cfd = db_fetch_object($results)) {
    $list['serie'][$cfd->cfdr_id] = array('#value' => $cfd->serie);
    $list['folio'][$cfd->cfdr_id] = array('#value' => $cfd->folio);
    $list['emisor_rfc'][$cfd->cfdr_id] = array('#value' => $cfd->emisor_rfc);
    $list['date'][$cfd->cfdr_id] = array('#value' => date_format_date(date_make_date($cfd->fecha_cfd), 'medium'));
    $list['receptor_rfc'][$cfd->cfdr_id] = array('#value' => $cfd->receptor_rfc);
    $list['links'][$cfd->cfdr_id] = array('#value' => cfdr_get_dl_links(basename($cfd->xml_filename), $cfd->cfdr_id));
  }
  $list['pager'] = array('#value' => theme('pager', NULL, 30, 0));
  $form['list'] = $list;
  $form['#theme'] = 'cfdr_view_cfds';

  return $form;
}

/**
 * Returns the xml file of the cfd node for download.
 * @param StdObject $node
 */
function cfdr_download_xml($cfdr_id) {
 $filename = cfdr_load_filename($cfdr_id);
 $basename = basename($filename);
 $headers = array(
   'Content-Description: File Transfer',
   "Content-Disposition: attachment; filename=$basename",
   'Content-type: text/xml',
 );
 // Code based on file_transfer() but modified to serve files outside the
 // drupal file system
 if (ob_get_level()) {
   ob_end_clean();
 }

 foreach ($headers as $header) {
   // To prevent HTTP header injection, we delete new lines that are
   // not followed by a space or a tab.
   // See http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
   $header = preg_replace('/\r?\n(?!\t| )/', '', $header);
   drupal_set_header($header);
 }

 // Transfer file in 1024 byte chunks to save memory usage.
 if ($fd = fopen($filename, 'rb')) {
   while (!feof($fd)) {
     print fread($fd, 1024);
   }
   fclose($fd);
 }
 else {
   drupal_not_found();
 }
 exit();
}

/**
 * Gets the out of the node and gets the PDF from cfd_make_pdf() then
 * sends it to the browser.
 * @param StdObject $node
 */
function cfdr_download_pdf($cfdr_id) {
  //generate PDF
  $pdf = cfd_make_pdf(cfdr_load_filename($cfdr_id));
  //send generated file to browser
  $pdf->SetTitle($node->title);
  $pdf->SetDisplayMode('fullpage');
  $pdf->Output("$node->title.pdf");
}

/**
 * returns the links string to download this cfd node as xml or pdf by using l()
 * @return String link
 */
function cfdr_get_dl_links($basename, $cfrd_id) {
  // add $node_title.pdf to PDF dl path so Adobe Reader gets that as a filename
  return  l('PDF', "cfdr/$cfrd_id/pdf/$basename.pdf") . ' | ' . l('XML', "cfdr/$cfrd_id/xml");
}

/*
 * Implementation of hook_cron().
 */
function cfdr_cron() {
  cfdr_scan();
}

/**
 * Scans for .xml cfds in configured directory and moves XML CFDs to another dir
 **/
function cfdr_scan() {
  $scan_path = variable_get('cfdr_scan_path', 'sites/default/cfd');
  $move_path = variable_get('cfdr_move_path', 'sites/default/cfd/scanned');
  if ($files = file_scan_directory($scan_path, '.xml|.XML$', array('.', '..', 'CVS'), 0, FALSE)) {
    $count = 0;
    foreach ($files as $file) {
      $new_filename = $move_path . '/' . $file->basename;
      // move to $move_path
      if (rename($file->filename, $new_filename)) {
        // add entry to {cfdr} form .xml file
        cfdr_insert($new_filename);
        $count++;
      }
    }
  }
  watchdog('cfdr', '@count files imported succesfully', array('@count' => $count), WATCHDOG_NOTICE);
}
