<?php
/**
 * @file Main module file
 */

/**
 * Implementation of hook_menu().
 */
function cfdr_menu() {
  $menu = array();
  $menu['cfdr'] = array(
    'title' => 'View CFDs',
    'description' => 'View all CFDs',
    'access callback' => 'user_access',
    'access arguments' => array('view assigned FEs'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cfdr_view_cfds'),
  );
  $menu['cfdr/%cfdr/pdf'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Download',
    'access callback' => 'cfdr_access',
    'access arguments' => array('view', 1),
    'page callback' => 'cfdr_download_pdf',
    'page arguments' => array(1),
    'file' => './cfd.pdf.inc'
  );
  $menu['cfdr/%cfdr/xml'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Download',
    'access callback' => 'cfdr_access',
    'access arguments' => array('view', 1),
    'page callback' => 'cfdr_download_xml',
    'page arguments' => array(1),
  );
  $menu['cfdr/%cfdr/html'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'HTML View',
    'access callback' => 'cfdr_access',
    'access arguments' => array('view', 1),
    'page callback' => 'cfdr_view_html',
    'page arguments' => array(1),
  );
  //Admin menu
  $menu['admin/settings/cfdr'] = array(
    'title' => 'CFD - Received',
    'description' => 'Configure CFD - Received options',
    'access callback' => 'user_access',
    'access arguments' => array('administer cfdr'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cfdr_admin_form'),
    'file' => './cfdr.admin.inc',
  );
  return $menu;
}

/**
 * Implementation of hook_perm().
 */
function cfdr_perm() {
  return array('administer cfdr', 'view any CFD');
}


/**
 * Implementation of hook_access().
 * Enforces permissions described by hook_perm() for node type cfdr
 * @return boolean true if access granted.
 */
function cfdr_access($op, $node, $account = NULL) {
  global $user;
  if (!isset($account))
    $account = $user;

  return TRUE;
}

/**
 * 
 * @param StdObject $node (by reference)
 */
function cfdr_autofill_fields(&$node) {
  //parse XML file read (with xml DOM(simpleXML sucks at namespaces))
  $doc = new DOMDocument();
  $doc->loadXML($node->xml_file);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/2');
  $serie = $xpath->query('/cfd:Comprobante/@serie');
  $folio = $xpath->query('/cfd:Comprobante/@folio');
  $fecha_cfd = $xpath->query('/cfd:Comprobante/@fecha');
  $cliente_rfc = $xpath->query('/cfd:Comprobante/cfd:Receptor/@rfc');
  //now save into the node (->item(0) for first match)
  $node->fecha_cfd = $fecha_cfd->item(0)->value;
  $node->cliente_rfc = $cliente_rfc->item(0)->value;
  $node->title = $serie->item(0)->value . $folio->item(0)->value;
}

/**
 *
 */
function cfdr_insert($) {
  cfdr_autofill_fields($);
  
  
  //if $node->cliente_rfc matches a username, set $node->cliente_uid to that user
  $node->cliente_uid = cfdr_rfc2uid($node->cliente_rfc);

  if ($node->cliente_rfc == 'XAXX010101000') {
  drupal_write_record('cfdr', $);
}

/**
 * Implementation of hook_delete().
 */
function cfdr_delete(&$node) {
  db_query('DELETE FROM {cfd} WHERE cfdr_id = %d', $node->cfdr_id);
}

/**
 * Implementation of hook_load().
 */
function cfdr_load($node) {
  return db_fetch_object(db_query('SELECT * FROM {cfd} WHERE nid = %d AND vid = %d', $node->nid, $node->vid));
}

/**
 * Implementation of hook_view().
 */
function cfdr_view($node, $teaser = FALSE, $page = FALSE) {
//  return node_prepare($node, $teaser);
  if (!$teaser) {
    $node = node_prepare($node, $teaser);
    //add the other elements
    $node->content['cfdr_fields'] = array(
      '#value' => theme('cfdr_fields', $node),
      '#weight' => 4,
    );
  }
  else {
    $node = node_prepare($node, $teaser);
  }
  drupal_set_title(t('FE-@title', array('@title' => $node->title)));
  return $node;
}

function theme_cfdr_view_cfds($form) {
  //based on theme_node_admin_nodes() in core - node.admin.inc
  // If there are rows in this form, then $form['title'] contains a list of
  // the title form elements.
  $has_posts = isset($form['list']['title']) && is_array($form['list']['title']);
  $header = array(t('FE #'), t('Date'), t('Download'));

  $output = '';

  $output .= drupal_render($form['date_filter']);
  if ($has_posts) {
    foreach (element_children($form['list']['title']) as $key) {
      $row = array();
      $row[] = drupal_render($form['list']['title'][$key]);
      $row[] = drupal_render($form['list']['date'][$key]);
      $row[] = drupal_render($form['list']['links'][$key]);
      $rows[] = $row;
    }
  }
  else {
    $rows[] = array(array('data' => t('No CFDs available.'), 'colspan' => '3'));
  }

  $output .= theme('table', $header, $rows);
  if ($form['pager']['#value']) {
    $output .= drupal_render($form['pager']);
  }

  $output .= drupal_render($form);

  return $output;
}

function cfdr_view_cfds() {
  global $user;
  $form = cfdr_datefilter_form();
  
  // construct and execute the query
  $basic_query = 'SELECT {cfd}.nid, {cfd}.fecha_cfd, {node}.title FROM {cfd} INNER JOIN {node} ON {cfd}.vid = {node}.vid WHERE {node}.status = 1';
  if ($user->uid != 1)
    $basic_query .= " AND {cfd}.cliente_uid = $user->uid";
  
  if (isset($_SESSION['cfds_filter'])) {
    $start = $_SESSION['cfds_filter']['start'];
    $end = $_SESSION['cfds_filter']['end'];
    $basic_query .= " AND {cfd}.fecha_cfd >= '$start' AND {cfd}.fecha_cfd <= '$end'";
  }
  $results = pager_query($basic_query . ' ORDER BY {cfd}.fecha_cfd ASC', 10);
  
  // construct the list
  $list = array();
  while ($cfd = db_fetch_object($results)) {
    $list['title'][$cfd->nid] = array('#value' => l($cfd->title, "node/$cfd->nid"));
    $list['date'][$cfd->nid] = array('#value' => date_format_date(date_make_date($cfd->fecha_cfd), 'short'));
    $list['links'][$cfd->nid] = array('#value' => cfdr_get_dl_links($cfd->title, $cfd->nid));
  }
  $list['pager'] = array('#value' => theme('pager', NULL, 10, 0));
  $form['list'] = $list;
  $form['#theme'] = 'cfdr_view_cfds';

  return $form;
}

/**
 * 
 */
function cfdr_datefilter_form() {

}

function cfdr_datefilter_form_validate($form, &$form_state) {

}

/**
 * Returns the xml file of the cfd node for download.
 * @param StdObject $node
 */
function cfdr_download_xml($node) {

}

/**
 * looks for the RFC as username in the {users} table.
 * @param string $rfc
 *   Looks for this username
 * @return
 *   UID of the corresponing RFC/username. IF not found returns 1.
 */
function cfdr_rfc2uid($rfc) {
  $result = db_result(db_query("SELECT uid FROM {users} WHERE name='%s'", $rfc));
  //if no user matches, return admin user
  if (!$result)
    return 1;
  else
    return $result;
}

/**
 * returns the links string to download this cfd node as xml or pdf by using l()
 * @return String link
 */
function cfdr_get_dl_links($node_title, $node_nid) {
  // add $node_title.pdf to PDF dl path so Adobe Reader gets that as a filename
  return  l('PDF', "node/$node_nid/download/pdf/$node_title.pdf") . ' | ' . l('XML', "node/$node_nid/download/xml");
}

/*
 * Implementation of hook_cron().
 */
function cfdr_cron() {
  cfdr_scan();
}

/**
 * Scans for .xml cfds in configured directory and moves XML CFDs to another dir
 **/
function cfdr_scan() {
  $scan_path = variable_get('cfdr_scan_path', 'sites/default/cfd');
  $move_path = variable_get('cfdr_move_path', 'sites/default/cfd/scanned');
  if ($files = file_scan_directory($scan_path, '.xml|.XML$', array('.', '..', 'CVS'), 0, FALSE)) {
    foreach ($files as $file) {

    }
  }
}
